services:
  - type: web
    name: my-flask-app
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: gunicorn --bind 0.0.0.0:5000 run:app
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: DATABASE_URL
        fromDatabase:
          name: my-flask-db
          property: connectionString

databases:
  - name: my-flask-db
    region: oregon
    plan: free
    postgresVersion: 13
